### ISSUE TITLE
Could not find com.android.tools.build:gradle:4.0.0.

### ISSUE THREAD

**Issue by MoE3s3** [gradle/android-cache-fix-gradle-plugin#100]
how can solve this

**Comment by runningcode** [comment]
Thanks for the report. Can you please tell us more information about this error? Do you have a full stack trace or console logs from the error?
It might also help to add the `build.gradle` file where this is happening.
That being said, it looks like an error with the Android Gradle Plugin. You can find instruction on how to use that here. https://developer.android.com/studio/releases/gradle-plugin#updating-plugin

**Comment by MoE3s3** [comment]
Could not find com.android.tools.build:gradle:4.0.0.
Searched in the following locations:
  -
https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.0.0/gradle-4.0.0.pom
  -
https://jcenter.bintray.com/com/android/tools/build/gradle/4.0.0/gradle-4.0.0.pom
Required by:
    project :
Open File

* I did't get any solution for in at the linke that you share

**Comment by runningcode** [comment]
Can you share your `build.gradle` file? Or run the build with `--scan` and share a link to the build scan?

Are you trying to apply the Gradle Android Cache Fix plugin or are you just having issue with the Android Gradle Plugin?

**Comment by MoE3s3** [comment]
// Top-level build file where you can add configuration options common
to all sub-projects/modules.
buildscript {
    repositories {

        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by MoE3s3** [comment]
I installed android studio last night I dont changed any thing all of it
its default settings installed with android studio

keep in mind I am not professional to deal with this IDE bcz I am a student
started to learn android for week age from youtube thats mean I can't
understand any thing you say so give me steps .. sorry for that 🙂 and
thanks for your time

**Comment by runningcode** [comment]
Hey @MoE3s3 thanks for filing this. Unfortunately this does not seem related to this android cache fix plugin. If you need help with the Android Gradle plugin, please file a bug with b.android.com.
For Gradle specific issues, you can check out the [Gradle Community slack](https://gradle.com/slack-invite) or the [Gradle community forum](https://discuss.gradle.org/)

**Comment by MoE3s3** [comment]
Thanks its solved .. its about vpn issue
