### ISSUE TITLE
Provide option to disable build cache for specific task

### ISSUE THREAD

**Issue by ganadist** [gradle/android-cache-fix-gradle-plugin#112]
Sometimes, Android Gradle Plugin can be released with build cache bugs.

https://issuetracker.google.com/issues/148084493
https://issuetracker.google.com/issues/160909142

And these bugs can be annoying, because developer let clear build cache whenever perform build.
Also, if gradle remote build cache is enabled,  productivity is greatly reduced, because contamination of the build cache propagates.

Even so, turning off all build caches makes the build speed too slow.
So if plugin provides to control build cache per task, it can prevent productivity decline.

X-posted on https://issuetracker.google.com/issues/162524633 , because I am not sure which component(android gradle plugin or cache-fix plugin) is suitable for this role.

**Comment by runningcode** [comment]
@ganadist You can disable caching for a specific task with the following code
```
tasks.named("<taskName>").configure {
  outputs.cacheIf { false }
}
```

**Comment by ganadist** [comment]
@runningcode , Thank you very much!
