### ISSUE TITLE
Multiple input file properties 'rawLocalResources.workaround'

### ISSUE THREAD

**Issue by cdsap** [gradle/android-cache-fix-gradle-plugin#124]
Hi, thanks for this plugin,
we are testing AGP 4.1.0 with android-cache-fix-gradle-plugin 1.0.12 (Gradle 6.5.1).
The task `mergeVARIANTResources` in our main module  is failing with:
```
Multiple input file properties with name 'rawLocalResources.workaround'
```
When we disable the plugin the build works ok. 
Thanks

**Comment by n8ebel** [comment]
We're seeing something very similar

```
Execution failed for task ':common:packageDebugResources'.
> Multiple input file properties with name 'rawLocalResources.workaround'
```

- AGP 4.1.0
- Gradle 6.7
- android-cache-fix-gradle-plugin 1.0.13

**Comment by runningcode** [comment]
Thanks for reporting. Could you paste the full stacktrace here? (Run build with `--stacktrace`. Or share a link to a build scan? Run the build with `--scan`.

**Comment by n8ebel** [comment]
@runningcode Thanks for the suggestion!  It looks like we had previously added a similar workaround manually.  Removing that code seems to have resolved the issue for us.

**Comment by runningcode** [comment]
Pretty sure I sent both of you the workaround and you applied it manually before we incorporated it in to the cache fix plugin. I'm going to close this out then.
