### ISSUE TITLE
temporarySchemaLocationDir issue after updating to 2.0.0

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [gradle/android-cache-fix-gradle-plugin#137]
### Task
`./gradlew app:assembleDebug`

### Error output

```
[2021-02-01T17:13:14.901Z] * What went wrong:
[2021-02-01T17:13:14.901Z] Execution failed for task ':phone:kaptKotlin'.
[2021-02-01T17:13:14.901Z] > Cannot get property 'temporarySchemaLocationDir' on null object
```

### Description
After upgrading the plugin to `2.0.0`, we're always having issue to build the app. The module it breaks seems to be random, but none of them have `room` dependency.

Here's a diff of what have been done after updating to plugin `2.0.0` (I've done that to this `database` module and other modules that depend on `room`).
![image](https://user-images.githubusercontent.com/45950956/106493984-9d316a00-6498-11eb-9f6f-ee8022617db2.png)

**Comment by ghale** [comment]
I believe this is the same as #135, fixed with version 2.0.1 of the cache fix plugin.  Can you give it a try and see if that resolves the issue?
