### ISSUE TITLE
Support Android gradle plugin 4.1.2

### ISSUE THREAD

**Issue by prcaen** [gradle/android-cache-fix-gradle-plugin#138]
Hey,

plugin version: `2.0.1`

In `README.md` you are saying that Android Gradle Plugin 4.1.2 is supported.
But it's seems to no be referenced as supported in  `build.gradle` (`supportedVersions`).

Is it supported or not?

Thanks

**Comment by ghale** [comment]
Bah, this was just due to a bad merge that wasn't noticed.  4.1.2 is supported.  We have been testing against it in the past and I've fixed this, so we'll be testing against it in the future, too.  

Thanks for pointing this out!
