### ISSUE TITLE
compileDebugLibraryResources fails when reusing the configuration cache

### ISSUE THREAD

**Issue by CristianGM** [gradle/android-cache-fix-gradle-plugin#148]
AGP 4.1.2
Both Gradle 6.8.3 and 7.0-milestone-2
org.gradle.android.cache-fix 2.1.2

When running `./gradlew :lib:assembleDebug` on a library and it reuses the configuration cache the build fails with:

> Execution failed for task ':lib:compileDebugLibraryResources'.
> > Could not find method setPropertyValue() for arguments [task ':lib:compileDebugLibraryResources', property(org.gradle.api.file.Directory, undefined)] on task ':lib:compileDebugLibraryResources' of type com.android.build.gradle.tasks.CompileLibraryResourcesTask.
> 

The stack trace is:

> Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method setPropertyValue() for arguments [task ':lib:compileDebugLibraryResources', property(org.gradle.api.file.Directory, undefined)] on task ':lib:compileDebugLibraryResources' of type com.android.build.gradle.tasks.CompileLibraryResourcesTask.
> at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:184)at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:167)at com.android.build.gradle.tasks.CompileLibraryResourcesTask_Decorated.invokeMethod(Unknown Source)at org.gradle.android.workarounds.CompileLibraryResourcesWorkaround_4_0$_apply_closure2$_closure4.doCall(CompileLibraryResourcesWorkaround_4_0.groovy:52)

**Comment by runningcode** [comment]
Hi @CristianGM are you facing this issue with Android Gradle Plugin `4.2.X`? `4.1.X` is not compatible with the configuration cache.

**Comment by CristianGM** [comment]
4.1.x is not fully compatible with configuration cache, but it works (I think the only issue I've seen is Lint)
Haven't tried with 4.2 I think.

**Comment by runningcode** [comment]
Interesting, your build is fully configuration cache compatible when the android Cache fix plugin is _not_ appiled in `4.1` but fails when it is applied?

**Comment by CristianGM** [comment]
Exactly

**Comment by runningcode** [comment]
@plastiv do you have a build scan you can share with us?

**Comment by plastiv** [comment]
Here https://scans.gradle.com/s/yrrwsfxppfysg/failure#1

**Comment by runningcode** [comment]
Thank you very much for the reproducer. We will take a look. 👀
