### ISSUE TITLE
ReadMe fix

### ISSUE THREAD

**Issue by timothy** [gradle/android-cache-fix-gradle-plugin#153]
In the readme it says: "Supported Android Gradle Plugin versions: 3.5.4, 3.6.4, 4.0.1, 4.1.2, 4.2.0-beta05, 7.0.0-alpha06"

It does not look like there is any Android Gradle Plugin with the version of `4.1.2`.  [Reference](https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle)

Maybe it meant [`4.1.0`](https://developer.android.com/studio/releases/gradle-plugin#4-1-0) instead?

**Comment by etiennestuder** [comment]
4.1.2 is correct. See https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
