### ISSUE TITLE
Update in CompileLibraryResourcesTask implementation 

### ISSUE THREAD

**Issue by plastiv** [gradle/android-cache-fix-gradle-plugin#170]
According to https://issuetracker.google.com/issues/141301405#comment11 partial fix is available on mac and linux at (I assume) AGP 7.0-alpha16 with

> android.experimental.enableSourceSetPathsMap=true
android.experimental.cacheCompileLibResources=true

What is the path forward to agp-cache-fix-plugin implementation:
* wait until full fix is provided by Google
* continue to use agp-cache-fix-plugin overwrite
* check for properties and siable agp-cache-fix-plugin overwrite
?

**Comment by gabrielittner** [comment]
I'd also be interested in knowing how the cache fix plugin behaves when those 2 properties are set. Can the combination of enabling them and the current behavior of the cache fix plugin lead to any issues? Maybe the plugin isn't needed at all with 7.0, `CompileLibraryResourcesTask` and `MergeResources` are resolved by this and `DexFileDependenciesTask` is also  cacheable in 7.0. That only leaves the Room workaround if you are using it

**Comment by runningcode** [comment]
Thanks for bringing this up. @plastiv @gabrielittner .
Do you know if when these properties are enabled, is the CompileLibraryResourcesTask cache-relocateable?
If so it might make sense to disable the workarounds in those cases.
Otherwise are you seeing any issue with cache relocateability in your project to report here?
Do you know specifically what these properties do?

**Comment by gabrielittner** [comment]
> Do you know if when these properties are enabled, is the CompileLibraryResourcesTask cache-relocateable?
> If so it might make sense to disable the workarounds in those cases.
When I tested it with 2 local clones of a project `CompileLibraryResourcesTask` was always taken from cache after enabling the 2 properties. However we don't have any Windows machines where flags apparently are not ready yet (at least according to the comment in the ticket linked above). 

I'm not sure about the merge resources task, but I can test that again next week when I'm back in the office. 

> Otherwise are you seeing any issue with cache relocateability in your project to report here?
If MergeResources is also working then all Android tasks are fine for us with 7.0. 

> Do you know specifically what these properties do?

I've only looked at that a bit and it seems like with them enabled relative paths are used as input

**Comment by gabrielittner** [comment]
I've tested it with this setyp: macOS, project checked out locally in 2 different directories, AGP 7.0.0, disabled cache fix plugin, both gradle properties enabled

All Android tasks that are cacheable were relocatable except for `MergeResources` in the `com.android.application` module (`rawLocalResourcesProcessRes` has absolute paths). `MergeResources` in library modules was relocatable, not sure why it is working there, but not in app modules. `CompileLibraryResourcesTask` and `DexFileDependenciesTask` were relocatable without any issues.

**Comment by runningcode** [comment]
Thanks for trying that out. We're looking in to making changes here to support this.
