### ISSUE TITLE
Disable caching of `MergeSourceSetFolders`

### ISSUE THREAD

**Issue by runningcode** [gradle/android-cache-fix-gradle-plugin#177]
This task does not benefit from caching.

`com.android.build.gradle.tasks.MergeSourceSetFolders`

Filed against Android here: https://issuetracker.google.com/issues/194804421

Temporary workaround:

```
tasks.withType(com.android.build.gradle.tasks.MergeSourceSetFolders).configureEach {
  outputs.cacheIf { false }
}
```

**Comment by matejdro** [comment]
It looks like upstream issue was closed?
