### ISSUE TITLE
Support for AGP 7.0.0

### ISSUE THREAD

**Issue by ILikeYourHat** [gradle/android-cache-fix-gradle-plugin#178]
Hi :) Android Studio Arctic Fox is out, so it would be nice to add support for AGP 7.0.0 into your plugin. Afaik there are two issues here:
- Explicit exception that is thrown: `java.lang.RuntimeException: Android plugin 7.0.0 is not supported by Android cache fix plugin. Supported Android plugin versions: 3.5.4, 3.6.4, 4.0.2, 4.1.3, 4.2.2, 7.0.0-beta05.`. I've tried to override this by adding `org.gradle.android.cache-fix.ignoreVersionCheck=true` in my `gradle.properties` file, but the exception persists.
- `com.android.build.gradle.BasePlugin` is now deprecated, so we need a new example how to integrate plugin into our app (or someone saying "the old way still works, please use it for now")

**Comment by vudzkostek** [comment]
Is it still needed? https://developer.android.com/studio/releases/gradle-plugin#build-cache-removed
I might be wrong cause I am not sure which cache is being fixed by this plugin :)

**Comment by ILikeYourHat** [comment]
@vudzkostek Yup, this plugin is about improving gradle caching in AGP, and that change is about AGP own caching mechanism  (already removed in version 4.1)

**Comment by runningcode** [comment]
1) You can override it by adding the system property to your `gradle.properties` file `systemProp.org.gradle.android.cache-fix.ignoreVersionCheck=true` while we work on updating the plugin.

2) It will work. If you have any trouble in your specific set up, please let us know.

**Comment by ILikeYourHat** [comment]
Thank you, it's working this way 😄
