### ISSUE TITLE
Cache miss when building this plugin: `:compileTestGroovy` and `:test` are out-of-date when unrelated file is changed

### ISSUE THREAD

**Issue by bigdaz** [gradle/android-cache-fix-gradle-plugin#196]
This is due to:
- The `versions.json` file will change with an unrelated file change in the repository. (eg change `.github/workflows/ci-check.yml`). [You can see why here](https://github.com/gradle/android-cache-fix-gradle-plugin/blob/master/build.gradle#L14). 
-  The `versions.json` file is then included in the runtime classpath when running the tests.

Here's a [build scan comparison](https://customer-scans.grdev.net/c/edyem7s4qwpqc/kj2p4isram6xk/task-inputs?cacheability=cacheable&expanded=WyIzb3ZzMzR1cGVyNHVnLWFzdHRyYW5zZm9ybWF0aW9uY2xhc3NwYXRoIiwiM292czM0dXBlcjR1Zy1hc3RUcmFuc2Zvcm1hdGlvbkNsYXNzcGF0aC0wLTAiLCJzaTZ1aHV6NHRkdWZ3LXN0YWJsZWNsYXNzcGF0aCIsInNpNnVodXo0dGR1Znctc3RhYmxlQ2xhc3NwYXRoLTEtMCIsInNpNnVodXo0dGR1ZnctcGx1Z2luY2xhc3NwYXRoIiwic2k2dWh1ejR0ZHVmdy1wbHVnaW5DbGFzc3BhdGgtMC0wIl0) showing the task input differences.

**Comment by runningcode** [comment]
@bigdaz i think this might be resolved due to how we now generate the version and versions.json file. can you confirm this is fixed?

**Comment by bigdaz** [comment]
Yep, I can no longer reproduce this issue. Closing.
