### ISSUE TITLE
Bump support for 7.0.3?

### ISSUE THREAD

**Issue by chrisjenx** [gradle/android-cache-fix-gradle-plugin#205]
7.0.3 was released a while back, this seems to work with it fine, can we just bump the supported to remove the warning.

(On that note, adding the warning ignore config line doesn't remove the warning)

**Comment by Farix1337** [comment]
In Version 7.X.X the AGP cache was removed https://developer.android.com/studio/releases/gradle-plugin#4.1-build-cache-removed does this affect the plugin?

**Comment by chrisjenx** [comment]
> In Version 7.X.X the AGP cache was removed https://developer.android.com/studio/releases/gradle-plugin#4.1-build-cache-removed does this affect the plugin?

Unrelated to this post, but no, if anything cashing probably works better now. Pre 7 we could never get remote cache too work. Now we get about a 80% hit ratio

**Comment by ghale** [comment]
Support for AGP 7.0.3 is in release 2.4.5.
