### ISSUE TITLE
False positive lint "cache" hit

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/android-cache-fix-gradle-plugin#217]
I just updated one of my projects to AGP 7 and found this bug: https://issuetracker.google.com/issues/211012777

I'm wondering if this mistaken up-to-date hit workaround would be considered as a "cache" fix?

**Comment by runningcode** [comment]
Thanks for filing this. From my understanding, this `lint.xml` file can be placed in any directory. For the generic fix in the Android Cache Fix plugin, is there a way to retrieve where the user has possibly placed this file?

**Comment by TWiStErRob** [comment]
As far as I understand each module can have its own, and it'll be used if lintOptions doesn't have the config file set.

Also this behaviour seems to be coming from lint itself, not AGP. But since AGP is wrapping it, Gradle must be aware of this implicit behaviour.

I'm not an expert in this area, just observed the behaviour, and the rest is reading the source code. :)

**Comment by runningcode** [comment]
We will accept PRs for this but given there is an easy workaround to this (declare the inputs) we will not prioritize working on this for now.
