### ISSUE TITLE
Support Gradle 4.4.1

### ISSUE THREAD

**Issue by lptr** [gradle/android-cache-fix-gradle-plugin#22]

**Comment by wolfs** [comment]
There is now a 4.4.1 snapshot: 4.4.1-20171218083510+0000

**Comment by xiirey2** [comment]
![image](https://user-images.githubusercontent.com/25363161/34343841-8648f70c-e991-11e7-80a7-78b31b4e3d59.png)

![image](https://user-images.githubusercontent.com/25363161/34343846-c4bba0e8-e991-11e7-91a5-f0a0aede0ce3.png)

please help.

**Comment by xiirey2** [comment]
Hi, is anybody out there for help, I am stuck with the above issue for a week.
Thanks.

**Comment by xiirey2** [comment]
![image](https://user-images.githubusercontent.com/25363161/34406264-da4f7b78-eb6c-11e7-97ac-033a9cb6e5f1.png)

**Comment by wolfs** [comment]
@xiirey2 I guess you are looking for this forum post/solution: https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457
The issue you are currently commenting on doesn't seem to have to do anything with the problem you are seeing? Do you use the `org.gradle.android.cache-fix` plugin?

**Comment by t---j** [comment]
@wolfs  I see `org.gradle.android.cache-fix` is not supported for `4.4.1` in my project

**Comment by wolfs** [comment]
@t---j Could you provide a little bit more of information? The `org.gradle.android.cache-fix` plugin version `0.2.5` should support Gradle `4.4.1`.

**Comment by lptr** [comment]
The latest version should support 4.4.1.
