### ISSUE TITLE
Please consider to publish new version

### ISSUE THREAD

**Issue by ganadist** [gradle/android-cache-fix-gradle-plugin#241]
Latest version(2.4.6) supports AGP 7.0.4, 7.1.0-beta04, and 7.2.0-alpha06.

But, Android Studio 2021.1.1 is released, and master branch supports 7.0.4, 7.1.1, 7.2.0-beta02

Please consider to publish new version.

**Comment by runningcode** [comment]
v2.5.0 is out: https://github.com/gradle/android-cache-fix-gradle-plugin/releases/tag/v2.5.0
