### ISSUE TITLE
Feature request: ability to suppress certain workarounds

### ISSUE THREAD

**Issue by ZacSweers** [gradle/android-cache-fix-gradle-plugin#289]
Would y'all be open to a PR to allow disabling workarounds by name? Some, such as the Room schema workaround, aren't applicable in our project but run every time anyway.

**Comment by ZacSweers** [comment]
This would also help workaround cases like [this](https://github.com/gradle/android-cache-fix-gradle-plugin/issues/285), since we could just disable that workaround if it's not needed anyway

**Comment by vanniktech** [comment]
Same for me. I don't use Room.

**Comment by runningcode** [comment]
We think it would be best if this workaround were automatically disabled when not needed. If not we will take a look and see if this is possible to add a switch to disable.

**Comment by runningcode** [comment]
Released in https://github.com/gradle/android-cache-fix-gradle-plugin/releases/tag/v2.5.7

Please use the *system property* `org.gradle.android.cache-fix.RoomSchemaLocationWorkaround.enabled=false`
