### ISSUE TITLE
Updated AGP fixes MergeResources

### ISSUE THREAD

**Issue by liutikas** [gradle/android-cache-fix-gradle-plugin#367]
> MergeResources is not relocatable: https://issuetracker.google.com/issues/236001083

It has been fixed in 8.0.0-alpha01, see https://issuetracker.google.com/issues/246529491#comment5

**Comment by runningcode** [comment]
Thanks for the info @liutikas . What is your proposal here?

**Comment by liutikas** [comment]
Update this repos readme that this bug is fixed? Not sure what you normally do.

**Comment by runningcode** [comment]
Ah sorry I thought you were proposing a code change. I've attached a PR to adjust the readme: https://github.com/gradle/android-cache-fix-gradle-plugin/pull/368/
