### ISSUE TITLE
Mark tasks that always execute with `doNotTrackState`

### ISSUE THREAD

**Issue by runningcode** [gradle/android-cache-fix-gradle-plugin#417]
There are some tasks in the workaround that do no have up-to-date checks. We should mark them as [doNotTrackState](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#doNotTrackState-java.lang.String-)

**Comment by cdsap** [comment]
closing this issue. 
The specific task https://github.com/gradle/android-cache-fix-gradle-plugin/blob/v2.8.1/src/main/groovy/org/gradle/android/workarounds/room/task/RoomSchemaLocationMergeTask.groovy#L23 has been removed in #601
