### ISSUE TITLE
Fix version assumption in JdkImageWorkaroundTest

### ISSUE THREAD

**Issue by tylerbertrand** [gradle/android-cache-fix-gradle-plugin#426]
https://github.com/gradle/android-cache-fix-gradle-plugin/blob/main/src/test/groovy/org/gradle/android/JdkImageWorkaroundTest.groovy#L189

Make sure assumption covers correct AGP versions. (JDK Image issue was not fixed in 7.4.0)

**Comment by cdsap** [comment]
done #427
