### ISSUE TITLE
AGP 7.4.1 support

### ISSUE THREAD

**Issue by lwasyl** [gradle/android-cache-fix-gradle-plugin#428]
Just leaving a ticket to track support for 7.4.1 which was [released recently](https://developer.android.com/studio/releases/gradle-plugin#android-gradle-plugin-7.4.1-february-2023)

**Comment by runningcode** [comment]
This was completed in https://github.com/gradle/android-cache-fix-gradle-plugin/commit/107fe474a1150e63484d6743a291f4616e56ab6b and will be released soon.
