### ISSUE TITLE
User can read release notes in the plugin portal

### ISSUE THREAD

**Issue by erichaagdev** [gradle/android-cache-fix-gradle-plugin#437]
We should use the `description` field of the plugin declaration to specify release notes. Currently, it is always a static string. 

The `description` field is shown on the plugin portal for each published version. Setting the `description` field to release notes means they can be seen directly in the plugin portal, rather than only on GitHub. This makes release notes and changes much more discoverable for users wanting to update.

An example of this can be seen on the plugin portal page for `com.gradle.plugin-publish`: https://plugins.gradle.org/plugin/com.gradle.plugin-publish

**Comment by runningcode** [comment]
We should do this for all the plugins, not just the Android Cache Fix Plugin.
