### ISSUE TITLE
Support Android 3.1.0-beta4 & 3.2.0-alpha04

### ISSUE THREAD

**Issue by b95505017** [gradle/android-cache-fix-gradle-plugin#44]

**Comment by lptr** [comment]
Looks like some of the relocatability issues introduced in 3.2.0-alpha02 haven't been fixed yet. :(

Support for 3.1.0-beta4 is not a problem, though.

**Comment by lptr** [comment]
I'm going to close this as it is delivered as part of 0.3.5. Will add support for 3.2.0-alpha05 once it fixes the relocatability issues.
