### ISSUE TITLE
RoomSchemaLocationArgumentProvider added to Kapt modules

### ISSUE THREAD

**Issue by cdsap** [gradle/android-cache-fix-gradle-plugin#446]
When applying the Android Cache Fix Gradle plugin to a project using `kapt` the `RoomSchemaLocationArgumentProvider` is created always, even if the project is not using `room-compiler`.

# Steps to reproduce
1- Apply the plugin in one project using kapt without `room-compiler`
2- Add in the root build gradle file:
```
    tasks.withType<org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask>().configureEach {
        doLast {
            this@configureEach.annotationProcessorOptionProviders.forEach {
                println(it.toString())
            }
        }
    }
```
Result:
```
> Task :core:common:kaptDemoDebugKotlin
[dagger.hilt.android.plugin.HiltGradlePlugin$configureProcessorFlags$1$1@45020498, 
org.gradle.android.workarounds.RoomSchemaLocationWorkaround$KaptRoomSchemaLocationArgumentProvider@361e7a4b]
```

I tested with older versions (2.5.7, Sep 2022) and it's reproducible

**Comment by runningcode** [comment]
This was intentional. At the time there was no way around this without eagerly resolving dependencies. Do you see how this can be avoided?

**Comment by cdsap** [comment]
Not sure if it's possible. Ideally, we would check in which processor has been applied the room-processor and then avoid the unused configuration on kapt modules

**Comment by runningcode** [comment]
Let's not do this and instead favor Google's Room Plugin.
