### ISSUE TITLE
Kotlin DSL is shown first and Groovy DSL is collapsed in README

### ISSUE THREAD

**Issue by erichaagdev** [gradle/android-cache-fix-gradle-plugin#462]
The Kotlin DSL should be shown first and Groovy DSL should be collapsed. This will make it consistent with the Gradle Documentation (e.g. [here](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:hello_world)).

**Comment by cdsap** [comment]
because the scope of the plugin is exclusevely for Android projects, I would wait until Google defines kts as default for build scripts in Android projects. They are still pointing first to groovy https://developer.android.com/studio/build
