### ISSUE TITLE
Build is incompatible with configuration cache, tasks do not run in parallel

### ISSUE THREAD

**Issue by erichaagdev** [gradle/android-cache-fix-gradle-plugin#472]
The usage of [the `signing` plugin causes the build to be incompatible with configuration caching](https://ge.solutions-team.gradle.com/s/decfsgesazgzq/console-log?page=1#L37-L57). This is even true for local builds where artifacts do not need to be signed. We should ensure the build is compatible with configuration caching.

**Comment by cdsap** [comment]
just to clarify, this issue is related to executions building the repository.

The Android Cache Fix Plugin is compatible with Configuration Cache.

**Comment by erichaagdev** [comment]
> just to clarify, this issue is related to executions building the repository.
> 
> The Android Cache Fix Plugin is compatible with Configuration Cache.

Yes, absolutely. Thank you for that clarification.

**Comment by cdsap** [comment]
Closing this issue because is related to the Signing plugin and is expected to be compatible in 8.1
