### ISSUE TITLE
Cache miss in Ksp 1.8.10-1.0.9

### ISSUE THREAD

**Issue by cdsap** [gradle/android-cache-fix-gradle-plugin#482]
Since version 1.8.10-1.0.9,  Ksp adds in the input `pluginOptions` a CompilerPluginConfig with all the compiler arguments set in the KspTask. 
One of this compiler arguments is the command line argument provider set in the KspWorkaround producing a cache miss when we are building from different paths:
<img width="739" alt="Screenshot 2023-04-04 at 4 40 31 PM" src="https://user-images.githubusercontent.com/475733/229945844-a0d699db-d314-4f85-b330-c40c43ba87ce.png">

The Ksp change is https://github.com/google/ksp/pull/1212/files 

PR #481 raised this issue, we need to analyzed the Ksp changes and provide a proper configuration for the command line arguments in the Ksp workaround.

**Comment by runningcode** [comment]
We should raise a bug against KGP for this.

**Comment by gmazzo** [comment]
> We should raise a bug on KSP for this.

Not sure it's a KSP bug to be honest. This plugin is adding an argument with an absolute path for the schemas locations. I think it's legal for KSP to consider all its arguments as inputs and not use cache if they are different.

**Comment by cdsap** [comment]
Hi @gmazzo, 
let see one example without using this plugin:
Google released new documentation where is using CommandLineArgumentProviders with relative path sensitivity to configure room:
``` kotlin
class RoomSchemaArgProvider(
      @get:InputDirectory
      @get:PathSensitive(PathSensitivity.RELATIVE)
      val schemaDir: File,
 ) : CommandLineArgumentProvider {
      override fun asArguments() = listOf("room.schemaLocation=${schemaDir.path}")
 }
```
and then configure the processor with:
```kotlin
 extensions.configure<KspExtension> {
       arg(RoomSchemaArgProvider(File(projectDir, "schemas")))
 }
```
the assumption is this works because we are informing as relative path the input, but if we compare two build scans we have the same issue:
<img width="738" alt="Screenshot 2023-04-05 at 4 53 48 PM" src="https://user-images.githubusercontent.com/475733/230238764-e2c765fc-77e4-4840-8f60-07cc3eddfd02.png">
if we add as custom values the `pluginOptions` we will see the same type of difference:
``` 
com.google.devtools.ksp.symbol-processing.apoption=room.schemaLocation=/gradle-enterprise-gradle-build-validation/.data/03-validate-local-build-caching-different-locations/20230405T161217-642e0051/first-build_nowinandroid/core/database/schemas}
vs
com.google.devtools.ksp.symbol-processing.apoption=room.schemaLocation=/gradle-enterprise-gradle-build-validation/.data/03-validate-local-build-caching-different-locations/20230405T161217-642e0051/second-build_nowinandroid/core/database/schemas}
```

That's why we are pointing(initially) to Ksp. Ksp added an extra step where retrieves the existing options for the KspTask(one of these options is the CommandLineArgumentProviders) and includes them as input `pluginOptions`:

```kotlin
kspTask.pluginOptions.add(
         project.provider {
              CompilerPluginConfig().apply {
                   (kspTask as KspTask).options.get().forEach {
                       addPluginArgument(KSP_PLUGIN_ID, it)
                   }
              }
         }
) 
```
The CommandLineArgument has the relative path set but when Ksp adds the PluginArgument doesn't know about the path sensitivity of the CommandLineArgument input. And here is the problem. 

In your PR you're defining a relative path like:
```
 projectDir.relativePath(temporarySchemaLocationDir.get().asFile)
```
I think this could be a solution, but I want to confirm first with the Ksp team if we could define the CommandLineArgumentProviders as InternalSubpluginOption, because before the change the options were considered only as @Internal and now they are also considered as plugin arguments inputs.

**Comment by gmazzo** [comment]
Thanks for the detailed explanation! It makes a lot of sense now.

**Comment by runningcode** [comment]
Just for reference the bug is here: https://github.com/google/ksp/issues/1359 Thanks for filing @cdsap

**Comment by runningcode** [comment]
I will close this since the PR was merged.
