### ISSUE TITLE
Renovate not picking up new versions

### ISSUE THREAD

**Issue by eygraber** [gradle/android-cache-fix-gradle-plugin#489]
I use [Renovate](https://github.com/renovatebot/renovate) to update my dependencies, and the past few releases here haven't been picked up by Renovate.

**Comment by runningcode** [comment]
Hi @eygraber it sounds like you are having an issue with Renovate. Can you please file an issue with them?

**Comment by eygraber** [comment]
Yes, the issue was that I apply my repositories in a convention plugin, so renovate falls back to just using mavenCentral
