### ISSUE TITLE
Configuration cache input change in Gradle 8.1 is investigated

### ISSUE THREAD

**Issue by runningcode** [gradle/android-cache-fix-gradle-plugin#490]
When updating the `ConfigurationCacheTest` to use Gradle 8.1, the following message appears which prevents the configuration cache from being re-used. 

`Calculating task graph as configuration cache cannot be reused because an input to plugin 'com.android.internal.library' has changed.`

See this test execution: https://ge.solutions-team.gradle.com/s/okdyga6gfyuog/tests/:testAndroid8_0_0/org.gradle.android.ConfigurationCachingTest/plugin%20is%20compatible%20with%20configuration%20cache?focused-exception-line=0-6&top-execution=1

We should investigate why this is happening and file a bug with either Gradle BT or Google AGP.

**Comment by runningcode** [comment]
This is a bug in KAPT.

**Comment by eboudrant** [comment]
Hi @runningcode, looks like the slack link isn't public, do you have a public link to the issue?

**Comment by runningcode** [comment]
Thanks for pointing that out, it was the wrong link. I've updated it above.

**Comment by eboudrant** [comment]
Does it mean we can't update to Gradle 8.1+ before Kotlin 1.9 is released (or have configuration cache broken with kapt)?

**Comment by runningcode** [comment]
I am currently not aware of a workaround.
