### ISSUE TITLE
After upgrading AGP to 8.0.1, an exception occurs when compiling that the resource file cannot be found: Unresolved reference. However, I can successfully compile the project locally in Android Studio. Unsuccessful on Github Action

### ISSUE THREAD

**Issue by PeOS-China** [gradle/android-cache-fix-gradle-plugin#513]
After upgrading AGP to 8.0.1, an exception occurs when compiling that the resource file cannot be found: Unresolved reference. However, I can successfully compile the project locally in Android Studio. Unsuccessful on Github Action
### **abnormal**
<img width="1322" alt="image" src="https://github.com/gradle/android-cache-fix-gradle-plugin/assets/8873336/75ef13ee-aa62-4233-9fce-08856c83e386">

### **CI Setting**
<img width="746" alt="image" src="https://github.com/gradle/android-cache-fix-gradle-plugin/assets/8873336/c4965d6b-edbf-4999-a76c-3fd8dd2a8cf6">

**Comment by runningcode** [comment]
Hi @PeOS-China thanks for reporting. What version of the Android Cache Fix plugin are you using? Is this issue resolved when removing the Android Cache Fix plugin?

**Comment by PeOS-China** [comment]
This issue is not caused by the Android Cache Fix plugin, resubmit the issue at:https://github.com/gradle/gradle/issues/25185
