### ISSUE TITLE
AGP 8.0.2 warning with cachefix plugin version 2.7.1

### ISSUE THREAD

**Issue by zetbrush** [gradle/android-cache-fix-gradle-plugin#525]
Although plugin readme claims to support 
Supported Android Gradle Plugin versions: 7.0.4, 7.1.3, 7.2.2, 7.3.1, 7.4.2, **8.0.2**, 8.1.0-beta04 and 8.2.0-alpha05 
version, but getting WARNING: Android plugin 8.0.2 has not been tested with this version of the Android cache fix plugin (2.7.1)

**Comment by cdsap** [comment]
Hi, we just released 2.7.2, can you try it please?

**Comment by be1ski** [comment]
Please let us know when version 2.7.2 will be available on Maven

**Comment by runningcode** [comment]
Hi, please try again. It is now available in the plugin portal.

**Comment by zetbrush** [comment]
Thx @cdsap @runningcode , now its ok with 2.7.2
