### ISSUE TITLE
Support AGP 3.1.0 GA and 3.2.0-alpha08

### ISSUE THREAD

**Issue by lptr** [gradle/android-cache-fix-gradle-plugin#54]

**Comment by emartynov** [comment]
Waiting here :)
BTW why Google people just don't have your changes in own plugin?

**Comment by lptr** [comment]
The only issue not fixed in AGP 3.1.0 that this plugin fixes is https://issuetracker.google.com/issues/69243050. As the [`README.md`](https://github.com/gradle/android-cache-fix-gradle-plugin#android-cache-fix-gradle-plugin) says, you only need this plugin with 3.1.0 if you are using the data binding feature. If you apply this plugin with AGP 3.1.0 without using the data binding feature, it even prints a warning that you don't need it.

We are working closely with Android developers to fix the remaining issues in 3.2.0 GA, making this plugin unnecessary.

**Comment by emartynov** [comment]
I use Data Binding so asked. Finger crossed it will be in the AGP 3.2

**Comment by WonderCsabo** [comment]
@lgptr i see, that issue is not referenced in the source code, this is why i thought everything was fixed already. I am also using data binding. :)

**Comment by lptr** [comment]
Hi Csaba, the issue link for `DataBindingDependencyArtifacts_Workaround` was incorrect. Now it points to the only remaining problem. Thanks for reporting!
