### ISSUE TITLE
Disable caching for PackageForUnitTest task

### ISSUE THREAD

**Issue by bacecek** [gradle/android-cache-fix-gradle-plugin#550]
Recently I've created an issue in Google's tracker about PackageForUnitTest task: https://issuetracker.google.com/issues/292114808.
From my perspective, this task should not be cached because it runs very fast, but task output could take a lot of disk space on cache server in large projects.

**Comment by runningcode** [comment]
Thanks for filing. Do you have an example of the time it takes to execute this task and the corresponding output?
A build scan would help here.

**Comment by bacecek** [comment]
Unfortunately, I can't share build logs of our project because of NDA.

I've tried to reproduce it on fenix application from firefox-android repo: https://github.com/mozilla-mobile/firefox-android/
I ran a task `./gradlew :app:testDebugUnitTest --tests="org.mozilla.fenix.AppRequestInterceptorTest" --build-cache --scan`, here are build scan: https://gradle.com/s/3goayqkgaindi (hope you will see the results)
Here are durations:
> Duration | 0.958s |  
>-- | -- | --
>Task action execution | 0.024s |  
>Fingerprinting inputs | 0.001s |  
>Build cache | 0.870s

And build cache result:
> Build cache result
> Cache key | 7e478d2218e4a6d0ed6bc60fdcde092f |  
> -- | -- | --
> Cache artifact | 17.9 MiB / 2 entries |  
> Pack | 0.870s

As we can see here, packing a cache of the task output took longer than task execution. And the size of file `app/build/intermediates/apk_for_local_test/fenixDebugUnitTest/apk-for-local-test.ap_` is 27.9 MB on a disk. And this is the only one module. With a large number of modules in the project, and a large number of changes being merged every day, the cache size of only this task output could reach tens of gigabytes on the remote server after a few days.

**Comment by cdsap** [comment]
Hi @bacecek, thanks for the PR and issue. 
We spent some time measuring to verify that adding the workaround will satisfy all the users of the plugin. 
Our first measurements were with the project nowinandroid and we didn't notice enough benefit when disabling the task compared with the duration of the task under different cache outcomes.
However, to replicate the scenario we picked another project(Signal) that generates an output for the same tasks of 15.4 Mb. We created different scenarios with different cache nodes around the world and local cache configurations. 
The tests were executed in a GHA runner with 2 cpus and 6Gb of memory, the results are(ms):

|      | executed_cache_disabled | executed | local | us-east | europe-west | asia-south |
|------|-------------------------|----------|-------|---------|-------------|------------|
| mean |                     197 |     2214 |   331 |     725 |        1149 |       2053 |
| p25  |                  188.25 |     2083 |   326 |     567 |        1114 |       1715 |
| p50  |                     195 |     2162 | 327.5 |     624 |        1159 |       1799 |
| p75  |                   207.1 |   2287.8 |   328 |   739.2 |      1257.2 |       1854 |
| p90  |                   235.6 |   2540.4 | 367.1 |  1342.8 |        1335 |     4199.8 |
| p99  |                     238 |     2574 |   383 |    1440 |        1339 |       4783 |

We are good moving forward your PR.

Thanks
