### ISSUE TITLE
Readme on github shows support 8.1.1, but 2.7.3 only support 8.1.0

### ISSUE THREAD

**Issue by evilcat-x** [gradle/android-cache-fix-gradle-plugin#571]
Getting this warning with 2.7.3 and AGP 8.1.1

Android plugin 8.1.1 has not been tested with this version of the Android cache fix plugin, although it may work.  We test against only the latest patch release versions of Android Gradle plugin: 7.0.4, 7.1.3, 7.2.2, 7.3.1, 7.4.2, 8.0.2, 8.1.0, 8.2.0-alpha14.  If 8.1.1 is newly released, we may not have had a chance to release a version tested against it yet.  Proceed with caution.  You can suppress this warning with with -Dorg.gradle.android.cache-fix.ignoreVersionCheck=true.

I also tried to setup org.gradle.android.cache-fix.ignoreVersionCheck=true. in gradle setting file but it seems getting ignored

https://github.com/gradle/android-cache-fix-gradle-plugin/blob/v2.7.3/src/main/resources/versions.json

**Comment by be1ski** [comment]
➕

**Comment by cdsap** [comment]
Hi @evilcat-x, thanks for the report and sorry for the delay. 
Release 2.7.4 has been published. Includes AGP 8.1.1 test support.

Closing the issue
