### ISSUE TITLE
Extension of type 'AndroidConfig' does not exist.

### ISSUE THREAD

**Issue by balus13** [gradle/android-cache-fix-gradle-plugin#58]
If i have the plugin enabled, i get this error:
`Extension of type 'AndroidConfig' does not exist. Currently registered extension types: [ExtraPropertiesExtension, g]`

Gradle: 4.4.1
Android Gradle Plugin: 3.1.0
Cache fix plugin: 0.4.0

**Comment by lptr** [comment]
Can you please provide a build scan (`--scan`)? If that's not possible, a stacktrace (`--stacktrace`) would also be helpful.

**Comment by lptr** [comment]
Can you try without configure-on-demand? Also, can you please post the build scan?

**Comment by dvdrlee** [comment]
I've seen this exception when applying the plugin in the root build.gradle file. If you apply the plugin in your app level gradle file then it works
