### ISSUE TITLE
Extension name conflict with new `Androidx.room` Gradle Plugin

### ISSUE THREAD

**Issue by evilcat0x** [gradle/android-cache-fix-gradle-plugin#603]
[Room 2.6.0](https://developer.android.com/jetpack/androidx/releases/room#2.6.0)

> The new artifact for the Room Gradle Plugin has been added to Room with the id `androidx.room`, which solves various existing issues in Room regarding having inputs and outputs of schemas via Gradle annotation processor options.

Currently, attempting to use both `android-cache-fix` and `androidx-room` gradle plugins will have a `RoomExtension` name conflict.

**Comment by Goooler** [comment]
This had been fixed in #601.

**Comment by runningcode** [comment]
See https://github.com/gradle/android-cache-fix-gradle-plugin/issues/600
