### ISSUE TITLE
Release versions faster when a new AGP version is released

### ISSUE THREAD

**Issue by BraisGabin** [gradle/android-cache-fix-gradle-plugin#640]
This issue is to find a way to avoid this type of issues: #641, #639, #525, #216 and #215

Right now I feel that the releases are reactive. When someone open an issue a new version is released. And I have no complains on the celerity there, you are doing a great job in this regard.

The question would it be a way to move this to a proactive way? This "attacks" directly the way of work on this repo and I'm not even a contirbutor. But I would like to know what's missing.

The most "brute force" way that I can think of is to create a bot to check the last version of AGP and automatically create a new issue. But maybe we could think on a smarter way to do it.

**Comment by runningcode** [comment]
Please see this comment: https://github.com/gradle/android-cache-fix-gradle-plugin/issues/641#issuecomment-1876968516
