### ISSUE TITLE
Release a new version to support AGP 8.2.1

### ISSUE THREAD

**Issue by BraisGabin** [gradle/android-cache-fix-gradle-plugin#641]
> The Dependency Analysis plugin is only known to work with versions of AGP between 7.4.2 and 8.2.0-alpha16. You are using 8.2.1. Proceed at your own risk.

I'm getting this message while using the last versión of the plugin: 3.0

Related with #639

**Comment by runningcode** [comment]
Hi Brais. I'm sorry you are seeing this message. This plugin does not produce this message and is not called the Dependency Analysis plugin. I will close this issue.
If I am wrong, please point me to the code that produces this message.

**Comment by BraisGabin** [comment]
🤦‍♂️ my bad, so sorry.
