### ISSUE TITLE
Support Android Gradle Plugin 3.1.3

### ISSUE THREAD

**Issue by francescocervone** [gradle/android-cache-fix-gradle-plugin#68]
https://androidstudio.googleblog.com/2018/06/android-studio-313-bug-fix-update.html

**Comment by emartynov** [comment]
Is it still required for the 3.1.3?

**Comment by francescocervone** [comment]
It should be. The DataBinding issue is still not marked as fixed.
https://issuetracker.google.com/issues/69243050

**Comment by lptr** [comment]
Yes, for 3.1.x the data binding fixes are not in place yet. However, 3.2.0-alpha18 seems to have solved the problems. I'll be releasing a version of the plugin shortly.

**Comment by lptr** [comment]
0.5 released.
