### ISSUE TITLE
Refactor expected outcome file names in Android Cache Fix Gradle Plugin

### ISSUE THREAD

**Issue by clayburn** [gradle/android-cache-fix-gradle-plugin#694]
In Android Cache Fix Gradle Plugin, we have a set of expected outcome files here: https://github.com/gradle/android-cache-fix-gradle-plugin/tree/main/src/test/resources/expectedOutcomes

The file names match different versions of AGP. The result is that we have to change these filenames every time a new version of AGP comes in. This becomes quite tedious for example when Google releases alpha/beta versions of a specific release.

Instead, since we keep one of these files for each major/minor version pairing, it would be nice if the files simply followed the format `<major>.<minor>_outcomes.json`. This would reduce some of the tedium of keeping Android Cache Fix Gradle Plugin up to date.

**Comment by erichaagdev** [comment]
I think this can be closed in favor of the automated approach. See: https://github.com/gradle/android-cache-fix-gradle-plugin/pull/703

**Comment by clayburn** [comment]
Nice!
