### ISSUE TITLE
Update readme ?

### ISSUE THREAD

**Issue by juliocbcotta** [gradle/android-cache-fix-gradle-plugin#701]
Hello there folks, it seems some issues mentioned in the readme are [fixed](https://issuetracker.google.com/issues/132245929) (or tagged as [won't fix](https://issuetracker.google.com/issues/246529491)) maybe the readme could be updated to reflect the current state based in the latest releases of AGP?

Thanks for the great job

**Comment by runningcode** [comment]
The room issue is linked to from the readme here: https://github.com/gradle/android-cache-fix-gradle-plugin?tab=readme-ov-file#room

Maybe I'm overlooking, is there another place it should be removed from?

**Comment by juliocbcotta** [comment]
Yes, those issues are in the readme already, my question is if we couldn't remove from the readme since they seem to be solved in stable releases...

**Comment by runningcode** [comment]
I think it is valuable to keep it in the readme since it was an issue that used to be solved by the Android Cache Fix Plugin and now you need to use the Room Gradle Plugin in order to solve the issue.

**Comment by juliocbcotta** [comment]
humm OK, thanks
