### ISSUE TITLE
Add deprecation checks to integration tests

### ISSUE THREAD

**Issue by ghale** [gradle/android-cache-fix-gradle-plugin#79]
We currently don't check whether we add any new deprecations with the nasty hacks we do to workaround caching problems.  We should at least check and fail the test if a new deprecation is caused.  We should require a deprecation to be explicitly accepted if it's the only way to work around an issue.

**Comment by runningcode** [comment]
Is there a simple way of doing this @ghale ? Or does it involve parsing testkit logs for deprecation warnings?

**Comment by ghale** [comment]
I think it involves parsing the logs, but that it should also be pretty simple.  See how we do this in the Gradle tests: https://github.com/gradle/gradle/blob/be4603f6a1ecb209b26508d068927cb01cb730d4/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java#L1352-L1360.  We don't have to do anything as sophisticated as the Gradle test fixtures, but just add some simple checks to avoid these being inadvertently introduced.
