### ISSUE TITLE
Support AGP 4.0.0 GA

### ISSUE THREAD

**Issue by autonomousapps** [gradle/android-cache-fix-gradle-plugin#92]
It just dropped today. When I updated my project to use it, I got the following error from this plugin:

> Android plugin 4.0.0 is not supported by Android cache fix plugin. Supported Android plugin versions: 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 4.0.0-rc01.

**Comment by runningcode** [comment]
Thanks for the report. PR is open to support AGP 4.0.0 here https://github.com/gradle/android-cache-fix-gradle-plugin/pull/93

In the meantime, you can workaround this issue by adding the following to your gradle.properties file:

`systemProp.org.gradle.android.cache-fix.ignoreVersionCheck=true`

**Comment by autonomousapps** [comment]
Honestly @runningcode , I didn't want to add that workaround because I was confident it would get fixed quickly :D
